fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
    transition:
      repo: "puppetlabs/transition"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "2.1.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "2.3.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
  symlinks:
    puppet_agent: "#{source_dir}"
