fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
  forge_modules:
    inifile:
      repo: "puppetlabs/inifile"
      ref: "5.3.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "9.0.0"
    translate:
      repo: "puppetlabs/translate"
      ref: "1.2.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
    facts:
      repo: "puppetlabs/facts"
      ref: "1.4.0"
