fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
    transition: "puppetlabs/transition"
    inifile: "puppetlabs/inifile"
    apt: "puppetlabs/apt"
  symlinks:
    puppet_agent: "#{source_dir}"
