fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "8.4.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "5.3.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "9.0.0"
    translate:
      repo: "puppetlabs/translate"
      ref: "1.2.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
    facts:
      repo: "puppetlabs/facts"
      ref: "1.4.0"
