fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    transition: "puppetlabs/transition"
    inifile: "puppetlabs/inifile"
    apt: "puppetlabs/apt"
  symlinks:
    puppet_agent: "#{source_dir}"
