---
.gitignore:
  paths:
    - '.*.sw?'

# The Travis and Appveyor configurations for puppet_agent don't fit
# in the module_sync model yet
.travis.yml:
  unmanaged: true

# Requires the bundler_args to be supported.
# .travis.yml:
#   dist: trusty
#   script: 'bundle exec rake $CHECK'
#   before_install:
#     - bundle -v
#     - rm Gemfile.lock || true
#     - gem update --system
#     - gem --version
#     - bundle -v
#   docker_sets:
#   includes:
#     # Disabling 1.8.7 as it no longer plays nice
#     # - rvm: 1.8.7
#     #   env: PUPPET_GEM_VERSION="~> 3.7.5"
#     # - rvm: 1.8.7
#     #   env: PUPPET_GEM_VERSION="~> 3.8.1"
#     # Disabling as puppet-module-gems only supports ruby >= 2.1.X
#     # - rvm: 1.9.3
#     #   env: PUPPET_GEM_VERSION="~> 3.8.1"  FUTURE_PARSER="yes"

#     - rvm: 2.4.1
#       env: CHECK="validate lint"
#     - rvm: 2.1.0
#       env: PUPPET_GEM_VERSION="~> 3.8" FUTURE_PARSER="yes" CHECK=spec
#     - rvm: 2.1.5
#       env: PUPPET_GEM_VERSION="~> 4.0.0" CHECK=spec
#     - rvm: 2.1.9
#       env: PUPPET_GEM_VERSION="4.7.1" HIERA_GEM_VERSION="3.2.2" CHECK=spec
#     - rvm: 2.1.9
#       env: PUPPET_GEM_VERSION="~> 4.10" CHECK=spec
#     - rvm: 2.4.1
#       env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec

appveyor.yml:
  unmanaged: true

# The default.yml file should not be updated yet as it doesn't fit
# in the module_sync model yet
'spec/acceptance/nodesets/default.yml':
  unmanaged: true

Rakefile:
  extra_disabled_lint_checks:
  - 'disable_140chars'
  - 'disable_puppet_url_without_modules'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
  - 'disable_only_variable_string'

.gitattributes:
  # Currently the only ERB template is for the Windows install
  # batch file and should always be CRLF
  exclude:
  - "*.erb"

NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2015
