---
.rubocop.yml:
  default_configs:
    Layout/LineLength:
      Max: 260
    RSpec/NamedSubject:
      Enabled: false
    RSpec/SubjectStub:
      Enabled: false
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 4.30'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.9'
      - gem: beaker-docker
        version: '~> 0.3'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.22'
      - gem: github_changelog_generator
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: nokogiri
      - gem: 'bolt'
        version: '~> 3.0'
        condition: 'ENV["GEM_BOLT"]'
      - gem: 'beaker-task_helper'
        version: '~> 1.9'
        condition: 'ENV["GEM_BOLT"]'
appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  unmanaged: true
