---
language: ruby
sudo: false
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake validate lint spec
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.7.5"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.8.1"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.1"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.8.1"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.0.0"
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 4.8.0"
