---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_VERSION="3.7.5" FUTURE_PARSER=yes STRINGIFY_FACTS=no
    - rvm: 1.8.7
      env: PUPPET_VERSION="3.8.0" FUTURE_PARSER=yes STRINGIFY_FACTS=no
    - rvm: 1.9.3
      env: PUPPET_VERSION="3.8.0" FUTURE_PARSER=yes STRINGIFY_FACTS=no
    - rvm: 2.0.0
      env: PUPPET_VERSION="3.8.0" FUTURE_PARSER=yes STRINGIFY_FACTS=no
    - rvm: 2.1.6
      env: PUPPET_VERSION="4.0.0"
